version: '3.9'
services:
  service:
    build:
      context: .
      target: app
    env_file:
      - .env
    ports:
      - 8000:8000
    container_name: service
    networks:
      app-network:

networks:
  app-network: